# Test playbook
---
- hosts: all
  become: true
  vars:
    NS: TRAVIS
    openio_bootstrap: true
  roles:
    - role: users
    - role: repo
      openio_repository_no_log: false
      openio_repository_mirror_host: mirror2.openio.io
    - role: gridinit
      openio_gridinit_namespace: "{{ NS }}"
      #openio_gridinit_per_ns: true
    - role: namespace
      openio_namespace_name: "{{ NS }}"
    - role: role_under_test
      openio_rawx_namespace: "{{ NS }}"
      openio_rawx_serviceid: "5"
      openio_rawx_bind_port: 6201
      openio_rawx_volume: "/var/lib/oio/sds/{{ openio_rawx_namespace }}/am"
      openio_rawx_state: "present"
    - role: role_under_test
      openio_rawx_namespace: "{{ NS }}"
      openio_rawx_serviceid: "2"
      openio_rawx_bind_port: 6202
      openio_rawx_volume: "/var/lib/oio/sds/{{ openio_rawx_namespace }}/stram"
      openio_rawx_state: "absent"
    - role: role_under_test
      openio_rawx_namespace: "{{ NS }}"
      openio_rawx_serviceid: "3"
      openio_rawx_bind_port: 6203
      openio_rawx_volume: "/var/lib/oio/sds/{{ openio_rawx_namespace }}/gram"
      openio_rawx_state: "offline"
...
